######################## default configuration ####################
baseURL = "/"
languageCode = "fr"
title = "Growth Hacking Experiments"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""


########################### Code color (before arrays) ############## 
PygmentsCodeFences = true
PygmentsStyle = "colorful"


[outputs]
  home = ["HTML", "RSS", "JSON"]


############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1
  
  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2
  
  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Growth Hacking Experiments est un blog à destination des marketeurs techniques fans de code et d'automatisation"
author = "Mikael Monjour"
# Google Analitycs
googleAnalitycsID = "UA-170765004-1"
# Contact Information
mobile = "0124857985320"
email = "growthackingexperiments\n@gmail.com"
location = "Paris, France"
# copyright
copyright = "| copyright &copy; 2020 [Eduba](https://www.eduba.school/) MIT (Non au contenu dupliqué !) |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Rejoignez notre newsletter"
content = "Pour rester informé des découvertes techniques toutes les semaines on à besoin de votre email pour vous recontacter"

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/groups/growthhaking/"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/MikaelMonjour/"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/GrowtHackingExperiments"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/mikaelmonjour/"
